name: safejourney
description: The Mobile App for the Safe Journey Platform

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  rxdart: ^0.22.0
  intl: ^0.16.0
  image_picker: 0.6.2+3
  sqflite: ^1.1.0
  path_provider: ^1.1.0
  http: ^0.12.0+2
#  encrypt: ^3.0.0

  shared_preferences: ^0.5.2
  flutter_secure_storage: ^3.2.1+1
  crypto: ^2.0.6

  dio: ^2.1.13
  flushbar: ^1.5.0
  meta: ^1.1.6
#  catcher: ^0.2.3
  equatable: ^0.2.6

  provider: 3.0.0+1
  firebase_auth: 0.11.1+11
  firebase_core: 0.4.2+2
  curved_navigation_bar: ^0.3.0
  flutter_vector_icons: ^0.2.0
  cached_network_image: ^1.1.1
  flutter_bloc: ^0.20.0
  url_launcher: ^5.2.3
  geolocator: ^5.1.3
  flutter_spinkit: ^4.0.0
  uuid: 2.0.1
  cyberpaysdkflutter: 1.0.0+20
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/onboarding_screen_1.png
    - images/onboarding_screen_2.png
    - images/onboarding_screen_3.png
    - images/bus.png
    - images/bus.jpeg
    - assets/state.json
    - images/1.png
    - images/2.png
    - images/3.png
    - images/4.jpg
    - images/5.jpg
    - images/screen1.5.png
    - images/screen1.png
    - images/screen2.png
    - images/screen3.png
    - images/deal.jpg
    - images/keke.png
    - images/loader.gif
    - images/loader2.gif
    - images/empty.gif
    - images/error.gif
    - images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-BlackItalic.ttf
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-BoldItalic.ttf
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-ExtraBoldItalic.ttf
        - asset: fonts/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito-ExtraLightItalic.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-LightItalic.ttf
        - asset: fonts/Nunito-RegularItalic.ttf
        - asset: fonts/Nunito-SemiBoldItalic.ttf
        - asset: fonts/Nunito-SemiBold.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
